name: kubelet
on:
  schedule:
    - cron: '0 0 * * 0'
  push: ~
jobs:
  "kubelet-24":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: kubelet build
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          image: kubelet
          tag: v1.24.16
          path: kubelet/
          build_file: Dockerfile_1.24
  "kubelet-27":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: kubelet build
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          image: kubelet
          tag: v1.27.4
          path: kubelet/
          build_file: Dockerfile_1.27
  "kubelet-28":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: kubelet build
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          image: kubelet
          tag: v1.28.0
          path: kubelet/
          build_file: Dockerfile_1.28
