name: kubelet
on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    paths: kubelet/*
jobs:
  "kubelet":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: kubelet build
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          image: kubelet
          tag: v1.30.8
          path: kubelet/
          build_file: Dockerfile
