name: Kube Karp
on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    paths: kube-karp/*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          image: kube-karp
          path: kube-karp/
