name: Kube Karp
on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    paths: kube-karp/*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@master
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: kube-karp/
          push: true
          tags: ghcr.io/${{ github.repository }}/kube-karp
