name: minio-client
on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    paths: minio-client/*
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          image: minio-client
          path: minio-client/
