name: openpyxl
on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    paths: openpyxl/*
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: ssacli build
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          image: openpyxl
          path: openpyxl/
