name: ssacli
on:
  schedule:
    - cron: "0 0 * * 0"
  push: ~
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: ssacli build
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          image: stunnel
          path: stunnel/
